type: object
required: [dataset]
properties:
  dataset:
    type: string
    format: url
  n_neighbors:
    oneOf:
      - type: integer
    default: 20
  leaf_size:
    oneOf:
      - type: integer
    default: 30
  output_column:
    oneOf:
      - type: string
    default: abnormality
