$schema: https://json-schema.org/draft/2020-12/schema
description: BAG Pand als GeoJSON Feature

allOf:
  # Inherit the full GeoJSON Feature structure and its semantic annotations
  - $ref: bblocks://ogc.geo.features.feature
  # Add our own properties on top
  - properties:
      # "properties" here refers to the GeoJSON Feature's "properties" object
      properties:
        $ref: bblocks://geonovum.examples.bag.schema